### ISSUE TITLE
migrate to other elasticsearch client library

### ISSUE THREAD

**Issue by gerosalesc** [knockrentals/scrapy-elasticsearch#17]
I think [pyes](https://github.com/aparo/pyes/) won't be migrating to elasticsearch 2.x any time soon so the only serious alternative I see is [elasticsearch-py](https://github.com/elastic/elasticsearch-py)

**Comment by lljrsr** [comment]
+1

**Comment by jayzeng** [comment]
Not a fan of elasticsearch-py, but good point, PR is welcome or I will find some time to over the weekend to make the change.

**Comment by gerosalesc** [comment]
I think I could make some time to work on this next week, but if you get it done before that happens that would make me happy :+1:  . Also, If you don't like elasticsearch-py we could go with the wrapper elasticsearch-dsl.

**Comment by lljrsr** [comment]
Great to hear that :) !
@jayzeng Just out of curiousity.. why are you not a big fan of elasticsearch-py?
Having a quick look at both packages elasticsearch-py seems like the better choice, because it is the official client, has a simpler code structure, it supports python 3 and pyes is supposedly in ["Development Status :: 2 - Pre-Alpha" stage](https://github.com/aparo/pyes/blob/master/setup.py#L112)

**Comment by jenkin** [comment]
+1 Any news on that?

**Comment by jayzeng** [comment]
Looks like elasticsearch-py is offered by elastic, I will use it and work on it this week.

**Comment by jayzeng** [comment]
Here is the open PR (work in progress):
https://github.com/knockrentals/scrapy-elasticsearch/pull/21 

Will likely wrap it up tomorrow

**Comment by gerosalesc** [comment]
@jayzeng Have you looked into [elasticsearch-dsl](https://elasticsearch-dsl.readthedocs.org/en/latest/) ? it´s a higher level api for elasticsearch-py, also official.

**Comment by jenkin** [comment]
@gerosalesc for simple indexing, elasticsearch-py is enough, imho... es-dsl relies on es-py, so less dependencies in this case...

**Comment by jayzeng** [comment]
I finished the code changes, I will appreciate if you guys can code review or even fork my branch for testing. 
https://github.com/knockrentals/scrapy-elasticsearch/pull/21/files

I also added an example app (for personal testing) and to illustrate how to use the pipeline. 
https://github.com/jayzeng/dirbot

Let me know what you guys think!

**Comment by jenkin** [comment]
@jayzeng you wrote "Elastic Search Pipeline for scrappy **expanded with support for multiple items**", so now I can index also a list of items (as requested in #20 ), but without [Bulk Helpers](https://elasticsearch-py.readthedocs.org/en/master/helpers.html#bulk-helpers), right?

**Comment by jenkin** [comment]
@jayzeng there is a problem in [scrapyelasticsearch.py > index_item()](https://github.com/knockrentals/scrapy-elasticsearch/pull/21/commits/8fc4c480fba42d62c323de4cef6aca03d24f9c22#diff-8de81bc78eb94d622003ea65dc694a4dR45), maybe you mean `unique_key = uniq_key`...

**Comment by jenkin** [comment]
@jayzeng another problem in the [same function](https://github.com/knockrentals/scrapy-elasticsearch/pull/21/commits/8fc4c480fba42d62c323de4cef6aca03d24f9c22#diff-8de81bc78eb94d622003ea65dc694a4dR51)! :D

From `hashlib.sha1(unique_key).hexdigest()` to `hashlib.sha1(item[unique_key]).hexdigest()`.

**Comment by jayzeng** [comment]
@jenkin thanks for spotting the typo, they should be fixed now. I am going to send in another PR to address the bulk insertion. 

I am going to merge this PR, but feel free to comment (or even better, send in a PR!).

**Comment by jayzeng** [comment]
Now available at https://pypi.python.org/pypi/ScrapyElasticSearch/0.7
