### ISSUE TITLE
TypeError: sha1() argument 1 must be string or buffer, not list

### ISSUE THREAD

**Issue by J3tto** [knockrentals/scrapy-elasticsearch#18]
Hi,

Have the following issue when running the following spider before its added to ES.

The ES Key is set as "link".

Any help would be greatly appreciated.

```
import scrapy
import uuid

from compass.items import CompassItem

class DarkReadingSpider(scrapy.Spider):
    name = "darkreading"
    allowed_domains = ["darkreading.com"]
    start_urls = (
        'http://www.darkreading.com/rss_simple.asp',
    )

    def parse(self, response):
        for sel in response.xpath('//item'):
                item = CompassItem()
                item['id'] = uuid.uuid4()
                item['title'] = sel.xpath('title/text()').extract()
                item['link'] = sel.xpath('link/text()').extract()
                item['desc'] = sel.xpath('description/text()').extract()
                print item
                yield item
```

Output/Error:

> {'desc': [u'Two-thirds of IT security professionals say that network security has become more difficult over the last two years with growing complexity in managing heterogeneous network environments.'],
>  'id': UUID('0112e36e-50ce-4660-9072-da2a5fec09e6'),
>  'link': [u'http://www.darkreading.com/cloud/survey-shows-cloud-infrastructure-security-a-major-challenge-/d/d-id/1324872?_mc=RSS_DR_EDT'],
>  'title': [u'Survey Shows Cloud Infrastructure Security A Major Challenge ']}
> 2016-04-01 15:15:34 [scrapy] ERROR: Error processing {'desc': [u'Two-thirds of IT security professionals say that network security has become more difficult over the last two years with growing complexity in managing heterogeneous network environments.'],
>  'id': UUID('0112e36e-50ce-4660-9072-da2a5fec09e6'),
>  'link': [u'http://www.darkreading.com/cloud/survey-shows-cloud-infrastructure-security-a-major-challenge-/d/d-id/1324872?_mc=RSS_DR_EDT'],
>  'title': [u'Survey Shows Cloud Infrastructure Security A Major Challenge ']}
> Traceback (most recent call last):
>   File "/usr/local/lib64/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
>     current.result = callback(current.result, *args, **kw)
>   File "/usr/local/lib/python2.7/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 70, in process_item
>     self.index_item(item)
>   File "/usr/local/lib/python2.7/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 52, in index_item
>     local_id = hashlib.sha1(item[uniq_key]).hexdigest()
> TypeError: sha1() argument 1 must be string or buffer, not list

**Comment by jayzeng** [comment]
Hi @J3tto - what do you use as unique key (ELASTICSEARCH_UNIQ_KEY) in your settings.py? If id is your unique key, you can set something like below in your settings.py:

```
from scrapy import log

ITEM_PIPELINES = [
    'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline',
]

ELASTICSEARCH_SERVER = 'localhost' # If not 'localhost' prepend 'http://'
ELASTICSEARCH_PORT = 9200 
ELASTICSEARCH_USERNAME = ''
ELASTICSEARCH_PASSWORD = ''
ELASTICSEARCH_INDEX = 'index'
ELASTICSEARCH_TYPE = 'type'
ELASTICSEARCH_UNIQ_KEY = 'id'
ELASTICSEARCH_LOG_LEVEL= log.DEBUG
```

**Comment by jayzeng** [comment]
@J3tto feel free to re-open if you have other questions
