### ISSUE TITLE
Add support for multiple ES nodes

### ISSUE THREAD

**Issue by jenkin** [knockrentals/scrapy-elasticsearch#19]
In settings you can set ELASTICSEARCH_SERVER only by using a simple string. Pyes supports multiple hosts in ES initialization and this string is passed wrapped in a single-element list (see. [L50 in scrapyelasticsearch.py](https://github.com/knockrentals/scrapy-elasticsearch/blob/master/scrapyelasticsearch/scrapyelasticsearch.py#L50)).

It could be useful to set ELASTICSEARCH_SERVER also by using a list of hosts, maybe checking if the setting is actually a string or a list, ie via isistance().

**Comment by jayzeng** [comment]
@jenkin good idea, it is included in https://github.com/knockrentals/scrapy-elasticsearch/pull/21 (work in progress)

**Comment by jayzeng** [comment]
Now available at https://pypi.python.org/pypi/ScrapyElasticSearch/0.7
