### ISSUE TITLE
NTLM Authentification with elasticsearch server

### ISSUE THREAD

**Issue by jsgervais** [knockrentals/scrapy-elasticsearch#24]
Is there any way to provide NTLM credentials to the elasticsearch server ?

**Comment by jayzeng** [comment]
@jsgervais not familiar with the NTLM protocol, want to send in a PR?

**Comment by jsgervais** [comment]
Will look forward sending a PR in a couple weeks.

**Comment by jayzeng** [comment]
@jsgervais that will be awesome :)

**Comment by jsgervais** [comment]
Here it is: https://github.com/knockrentals/scrapy-elasticsearch/pull/26

It was easier to implement then what I thought, thanks to requests_ntlm library https://github.com/requests/requests-ntlm

I spent a few hours analysing  elasticsearch's python client lib (elasticsearch-2.3.0) to determine the required changes. I needed to provide a Transport class object that uses the requests library instead of urllib3 for connections, and setting the Session.auth with the NTML auth credentials. 

Crawlers can now set NTLM credentials when connecting to elasticsearch by adding theses configurations in it's settings.py

ELASTICSEARCH_AUTH = 'NTLM'  
ELASTICSEARCH_USERNAME = 'Domain\user'
ELASTICSEARCH_PASSWORD = 'password'

Please note I'm fairly new to python, so feel free to adapt the changes ;)

**Comment by jayzeng** [comment]
Thanks for your work, it looks awesome. As I mentioned previously, I have very little knowledge about ntlm and don't have an environment to test. If your changes work great for you, I am happy to merge it in and release a new version. Make sure you update the REMADE.md to reflect these new settings, and feel free to add yourself as a contributor, I am sure other users will find this useful :)

**Comment by jsgervais** [comment]
Looks good to me with both merges.  Can you create a new release?

**Comment by jayzeng** [comment]
@jsgervais just cut a new release!
