### ISSUE TITLE
'set' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Alborto** [knockrentals/scrapy-elasticsearch#25]
Something has gone wrong with my scrapy elasticsearch pipeline. If I leave the pipeline as active in my settings, it returns an AttributeError (see attached). However, if I comment the pipeline out, the script runs without issue. Thoughts?

![set object error](https://cloud.githubusercontent.com/assets/19677908/15695841/9788b7d4-27ee-11e6-9fce-615a76a98a99.PNG)
![set object error settings](https://cloud.githubusercontent.com/assets/19677908/15695872/d482db60-27ee-11e6-97c4-a5ded8760a73.PNG)

**Comment by jayzeng** [comment]
Are you using the latest version of this library?

**Comment by Alborto** [comment]
Yes. Latest version (so it tells me).
![latest version](https://cloud.githubusercontent.com/assets/19677908/15696046/4d10cd52-27f0-11e6-95f4-f5e8920dafd2.PNG)

**Comment by jayzeng** [comment]
@Alborto you were upgrading elasticsearch, try:

```pip install ScrapyElasticSearch --upgrade```

**Comment by Alborto** [comment]
No luck unfortunately :(
Gives me the same error. Is it possible (or likely) that I've managed to accidentally change something in a different file/package which is causing this...?
![no dice](https://cloud.githubusercontent.com/assets/19677908/15764140/f93c3b44-296b-11e6-8436-d7b744fe9946.PNG)

**Comment by jayzeng** [comment]
hmm, I honestly have no idea without seeing your code. By looking at the stacktrace, I don't see how it is related to this library, I can be wrong though.

**Comment by Alborto** [comment]
Well I've managed to get it working again. I had 
ITEM_PIPELINES = {
    'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline', 100
}

instead of 
ITEM_PIPELINES = {
    'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline': 100
}.

Somewhere along the line, I'd changed : to , :\

**Comment by Angela-shi** [comment]
hello ，have you solved this problem?  I also come across it .

**Comment by jayzeng** [comment]
@Angela-shi you may try what @Alborto posted above (which is required for older version of scrapy), or you can upgrade to the latest version of scrapy.
