### ISSUE TITLE
NTLM

### ISSUE THREAD

**Issue by gordonthompson** [knockrentals/scrapy-elasticsearch#30]
I needed to do a : 

**pip install requests_ntlm**

for this pipeline to work

**Comment by jayzeng** [comment]
@gordonthompson good catch, fixed in https://github.com/knockrentals/scrapy-elasticsearch/commit/ece3e3b98b1e1492a98e39c6b1f07289fe11505b

**Comment by jayzeng** [comment]
fix is pushed to pypi
