### ISSUE TITLE
Usage documentation outdated

### ISSUE THREAD

**Issue by mgur** [knockrentals/scrapy-elasticsearch#32]
Usage (Configure settings.py:)

ITEM_PIPELINES = [
'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline',
] 
seems to be deprecated in newer scrapy versions

now use
ITEM_PIPELINES = {
    'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline': 100,
}
(the number defines the order of the Pipelines, if you have more than one)
see: http://doc.scrapy.org/en/latest/topics/item-pipeline.html#activating-an-item-pipeline-component

**Comment by jayzeng** [comment]
Thanks for reporting it. https://github.com/knockrentals/scrapy-elasticsearch/pull/33/files is the fix.
