### ISSUE TITLE
Dynamically set on index/type?

### ISSUE THREAD

**Issue by jbasrai** [knockrentals/scrapy-elasticsearch#36]
Configuration for Elasticsearch index and type is done statically in `settings.py`. Is there a recommended approach to setting this during runtime, perhaps based on the item that is being piped?

**Comment by jayzeng** [comment]
@jbasrai can you elaborate more what exactly you are looking for? Seems to me ELASTICSEARCH_UNIQ_KEY will probably be the only thing that can be set dynamically.

**Comment by jbasrai** [comment]
Ok sure. Say I have an item:

```
class MyItem(Item):
	url = Field()
	title = Field()
	content = Field()
```

I'd like to index these items into different Elasticsearch types based on their `url` field, so possible types could be `reddit`, `facebook`, `google`, etc.

Is there a way this can be done?

**Comment by jayzeng** [comment]
hmm, don't think I fully understand. 'reddit, facebook, google' are all string, how will they have different types?

**Comment by jbasrai** [comment]
Sorry for the confusion. By type I mean an _Elasticsearch_ type, as defined in the `ELASTICSEARCH_TYPE` setting.  So say an item comes down the pipeline like:

{
    url: "reddit",
    title: "ama",
    content: "blah"
}

I'd like to index it into an Elasticsearch type based on the url string. e.g. `items/reddit`

**Comment by jayzeng** [comment]
Ah, sounds like you want to dynamically insert to different doc_type, which is possible. But I really dislike the idea of adding another settings (since there is already a long list of settings, which makes using the library more difficult), and I don't anticipate this being a popular feature request. 

For what you want to do, you just need to make one line (see my comment in code) change by overriding the index_item () in the ElasticSearchPipeline class, something like:

```
 def index_item(self, item):

        index_name = self.settings['ELASTICSEARCH_INDEX']
        index_suffix_format = self.settings.get('ELASTICSEARCH_INDEX_DATE_FORMAT', None)

        if index_suffix_format:
            index_name += "-" + datetime.strftime(datetime.now(),index_suffix_format)

        index_action = {
            '_index': index_name,
            '_type': item['url'],  // <- use url key 
            '_source': dict(item)
        }

        if self.settings['ELASTICSEARCH_UNIQ_KEY'] is not None:
            item_unique_key = item[self.settings['ELASTICSEARCH_UNIQ_KEY']]
            unique_key = self.get_unique_key(item_unique_key)
            item_id = hashlib.sha1(unique_key).hexdigest()
            index_action['_id'] = item_id
            logging.debug('Generated unique key %s' % item_id)

        self.items_buffer.append(index_action)

        if len(self.items_buffer) >= self.settings.get('ELASTICSEARCH_BUFFER_LENGTH', 500):
            self.send_items()
            self.items_buffer = []
```

Let me know what you think or you have any good idea on implementing this cleanly.

**Comment by jayzeng** [comment]
@jbasrai going to close this issue, let me know if you need any other help
