### ISSUE TITLE
Include S3 images field

### ISSUE THREAD

**Issue by devlesedi** [knockrentals/scrapy-elasticsearch#40]
I'm using [S3 feed export](https://scrapy.readthedocs.io/en/latest/topics/feed-exports.html#topics-feed-storage-s3) to download images during scraping. I'm able to download the images to my S3 bucket but it happens after scrapy-elasticsearch has already completed. How can I index the response from S3 to include the image s3 url along with my item to be indexed?

Example:
`item['thumbnail'] = 'https://s3-eu-west-1.amazonaws.com/image-url-response-from-s3`

**Comment by devlesedi** [comment]
I found out I just needed to reorder the Pipeline items accordingly. And now image processing happens before the indexing stage.

`ITEM_PIPELINES = [
    'scrapy.pipelines.images.ImagesPipeline',
    'scrapyelasticsearch.scrapyelasticsearch.ElasticSearchPipeline'
]`

**Comment by jayzeng** [comment]
Great, glad you figured it out. That's exactly what you need to do.
