### ISSUE TITLE
Time-based indices' name from scraped data

### ISSUE THREAD

**Issue by jenkin** [knockrentals/scrapy-elasticsearch#42]
The parameter ELASTICSEARCH_INDEX_DATE_FORMAT sets index suffix from scraping timestamp to the specified format (ie. -%Y%m%d). But I need to set it to a string or a datetime (of a given format) taken from the scraped item. Here is a simple solution with two more parameters (ELASTICSEARCH_INDEX_DATE_KEY and ELASTICSEARCH_INDEX_DATE_KEY_FORMAT): https://github.com/jenkin/scrapy-elasticsearch/commit/e834082442027e5f0f3a61a891c3fd0740a50f40.

**Comment by jayzeng** [comment]
@jenkin I like where we heading, want to check in a PR?

**Comment by jenkin** [comment]
Yep! https://github.com/knockrentals/scrapy-elasticsearch/pull/48 There is also the fix for https://github.com/knockrentals/scrapy-elasticsearch/issues/43, I don't know if it can be a problem for merging, now...

**Comment by jayzeng** [comment]
Thanks @jenkin! Merged
