### ISSUE TITLE
ELASTICSEARCH_SERVERS not really required

### ISSUE THREAD

**Issue by jenkin** [knockrentals/scrapy-elasticsearch#43]
Elasticsearch has two default values for host and port: localhost and 9200. So the ELASTICSEARCH_SERVERS paramater is not really required, because you can assume the previous default values. See https://github.com/jenkin/scrapy-elasticsearch/commit/e834082442027e5f0f3a61a891c3fd0740a50f40.

**Comment by jayzeng** [comment]
Good point, I will remove the check

**Comment by jayzeng** [comment]
https://github.com/knockrentals/scrapy-elasticsearch/commit/2157e9ab4fcedda6cd13ff9380c7d81be12e1526
