### ISSUE TITLE
NTLM authentication adds a dependency even if you don't need it

### ISSUE THREAD

**Issue by jenkin** [knockrentals/scrapy-elasticsearch#44]
It's the pip package [requests_ntlm](https://github.com/requests/requests-ntlm). I'm using Python 2.7.3 on Debian 7.11. Maybe you can import the ntlm module only if the ELASTICSEARCH_AUTH parameters has NTLM value?

**Comment by jsgervais** [comment]
I'm not sure it can be done if some parameters have some values, however, I think you can import a package when it's available with precompiling conditions and then assert in the code if it is available.

**Comment by jayzeng** [comment]
Looks like I can use extra_require in setup tools (https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), let me play around it

**Comment by jayzeng** [comment]
https://github.com/knockrentals/scrapy-elasticsearch/pull/47

**Comment by jayzeng** [comment]
@jenkin @jsgervais I made the changes and pushed a build to pypi, will be great if you guys can give it a test.

**Comment by jayzeng** [comment]
Going to close this issue, please re-open if it doesn't work.
