### ISSUE TITLE
Delete data from ES index before inserting data again ? 

### ISSUE THREAD

**Issue by punit07** [knockrentals/scrapy-elasticsearch#53]
As the title says, Is there any inbuilt command in this plugin, that clears existing data in ES before populating it again ? Thanks

**Comment by jayzeng** [comment]
Hmm, it sounds like you are looking for an upsert, which is the default behavior of elasticsearch. Why do you need to delete, then index? Did you run into any issues?

**Comment by punit07** [comment]
@jayzeng My issue was that I commented out the 

`#ELASTICSEARCH_UNIQ_KEY = 'url'  # Custom uniqe key`

So with every new crawl, it was inserting duplicates ..... As soon as I uncommented the above link and configured 'Uniq key' properly, all starting working perfectly. No more dupes with subsequent crawls and insertions. Cheers ...!
