### ISSUE TITLE
Location of scrapyelasticsearch.py file

### ISSUE THREAD

**Issue by punit07** [knockrentals/scrapy-elasticsearch#54]
Hi, I need to tweak this file "_scrapyelasticsearch.py_". Not sure where its located. My OS is Ubuntu 16.04. Can anyone please help ?

Thanks

**Comment by jayzeng** [comment]
@punit07 it is explained in http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory

**Comment by punit07** [comment]
Thanks @jayzeng That post was very helpful. Cheers ...!
