### ISSUE TITLE
Specifiy specific fields to index

### ISSUE THREAD

**Issue by maanas** [knockrentals/scrapy-elasticsearch#56]
I am also storing the raw html along with the items, but do not want to send that to ES index. Can we specify the specific fields which should be send to ES for indexeing

**Comment by jayzeng** [comment]
hmm, I don't fully understand what you meant by 'specify the specific fields'. Can you put some examples to illustrate?

**Comment by jayzeng** [comment]
Ah, I know what you mean now. It sounds to me you will need to make a decision whether to index the entire raw html or certain fields (which will be structured). If raw html is something you have to do and unstructured, how will you know which fields to specify?

**Comment by jayzeng** [comment]
@maanas free feel to re-open if you have any good idea
