### ISSUE TITLE
Lots of items missing in kibana when using elasticsearch pipeline, but available in csv export and another relational pipeline

### ISSUE THREAD

**Issue by msdos** [knockrentals/scrapy-elasticsearch#59]
I would like to know how to debug my situation: I have a postgresql pipeline that's working flawlessly, adding 2k items to my relational database when I run scrapy. I've installed scrapy-elasticsearch as well to be able to use elasticsearch along my postgresql, but after scraping when I get into kibana I have... 36 items. My index is the day the item was scraped, and even selecting "years ago" in kibana interface I only get 36 hits.

How and where do I debug to check where are things going wrong?

**Comment by BasEnem** [comment]
My first hunch is why you would scrape something twice. That's way more overhead than simply exporting your Postgres DB to Elasticsearch: https://discuss.elastic.co/t/indexing-data-in-bulk-from-sql-server/1491 is a good starting point.

Aside from that: have you tried running scrapy from the CLI? That usually helps me debugging things. Make sure you debug level is set to "debug" (default). Should give you plenty of information.
Documents in Elasticsearch are normally overwritten, so might be a problem there? Same ID somehow? If you use a separate index for each day, it's easier to prefix it. I name my indices scrapy-something, then in my Kibana settings I specify my index search as "scrapy-*", so all indexes are included by default. No need to specify dates than.

Hope this might help you a bit.

**Comment by msdos** [comment]
> My first hunch is why you would scrape something twice?

They aren't being scraped twice, since it's an item pipeline they are already scraped when I insert then into the databases. They are being used for different purposes, so I need both.

Scrapy is being run from CLI.

> Documents in Elasticsearch are normally overwritten, so might be a problem there? Same ID somehow?

Will try to check it out. The unique key shouldn't be having problems, but I'll take a look. At least is an idea. Thanks for the suggestion.

**Comment by jayzeng** [comment]
@msdos sorry for the late response, not sure if this is still an issue. Two things I can think of:
1) check your scraping log (what you set in LOG_FILE), it will show you the number of items scraped and indexed
2) Like @BasEnem pointed out, double check if item has unique id. Elasticsearch overrides document with the same the id (with an incremented version number).

**Comment by jayzeng** [comment]
@msdos any update on this? feel free to re-open if you need any further assistance

**Comment by msdos** [comment]
I needed to step down from it. Anyways, thank you both for trying to help.
