### ISSUE TITLE
flush/commit every ELASTICSEARCH_FLUSH_SIZE items, and flush at end.

### ISSUE THREAD

**Issue by danizen** [knockrentals/scrapy-elasticsearch#60]
I'll work on this; pretty basic - expect pull request.   If there's a way and I've missed it, let me know.

**Comment by jayzeng** [comment]
@danizen you can set the buffer size by specifying ELASTICSEARCH_BUFFER_LENGTH in settings.py (which is default to 500)

**Comment by danizen** [comment]
Thanks.
