### ISSUE TITLE
Pipeline sending data after spider_closed and opened again.

### ISSUE THREAD

**Issue by pythoncontrol** [knockrentals/scrapy-elasticsearch#63]
I am using [scrapy-redis](https://github.com/rmax/scrapy-redis).
My spider is [RedisSpider](https://github.com/rmax/scrapy-redis/blob/master/src/scrapy_redis/spiders.py#L125)
(from docs)
The class scrapy_redis.spiders.RedisSpider enables a spider to read the urls from redis. The urls in the redis queue will be processed one after another, if the first request yields more requests, the spider will process those requests before fetching another url from redis.

If i am right: [scrapy-elasticsearch sends data to elasticsearch after number of items](https://github.com/knockrentals/scrapy-elasticsearch/blob/master/scrapyelasticsearch/scrapyelasticsearch.py#L112) >= ELASTICSEARCH_BUFFER_LENGTH setting.

`
if len(self.items_buffer) >= self.settings.get('ELASTICSEARCH_BUFFER_LENGTH', 500):
  self.send_items()
  self.items_buffer = []
`

RedisSpider is waiting when idle, so if we send 600 urls to redis and our ELASTICSEARCH_BUFFER_LENGTH is 500, 100 urls wont be saved. Beacuse RedisSpider never closes.

So i [overrided spider_idle method](https://gist.github.com/pythoncontrol/4a39ecfc5532a3f24addfa9130326a9f):

Now spider closes when its idle. It works.

But using [this code](https://gist.github.com/pythoncontrol/64e0861e5a04a0e51643ebcf5851d722)
I keep running the spider in loop that never ends. So when it closes it runs again. 
If there are urls in redis queue they are crawled. Spider is closed, data is send to elasticsearch and spider restarts.
It works, but now the loop:
[]
1. Spider starts.
2. Spider reads urls from redis queue.
3. Spider parsing...
4. Spider finished. (last chunk of data sent to elasticsearch)
5. Spider started.
**6. Data is being sent to elasticsearch... ?**
And the loop continues...
1. Spider starts...
2. Spider reads urls from redis queue.
3...
[]

Here's log of the loop:
https://gist.github.com/pythoncontrol/4e88f5de253ca406b24885af0b4673fd

**Comment by kirankoduru** [comment]
> RedisSpider is waiting when idle, so if we send 600 urls to redis and our ELASTICSEARCH_BUFFER_LENGTH is 500, 100 urls wont be saved. Beacuse RedisSpider never closes.

Correct me if I am wrong but there may not be any correlation between the URLs and the `ELASTICSEARCH_BUFFER_LENGTH` unless each URL is scraping one item each.

**Comment by pythoncontrol** [comment]
@kirankoduru agreed

**Comment by jayzeng** [comment]
@pythoncontrol I don't have immediate answer, I have done similar thing with a different approach. Basically I used redis as a pub/sub, where my publisher issues new messages (what url to scrape) every minute and the subscriber spawns up new process to run scraper. 

Supervisor allows you to specify the number of concurrent processes, so you can run multiple spiders (best with different scraping targets) simultaneously.
