### ISSUE TITLE
What does 'ELASTICSEARCH_UNIQ_KEY' do?

### ISSUE THREAD

**Issue by Feelthewind** [knockrentals/scrapy-elasticsearch#66]
Is it for adding _id value? I added some documents and it didn't seem like that.. If so, is there any way to add id value? I want to use scraped urls as id.

**Comment by jayzeng** [comment]
@Feelthewind that's correct, it is used to construct a unique document id (see https://github.com/knockrentals/scrapy-elasticsearch/blob/master/scrapyelasticsearch/scrapyelasticsearch.py#L81-L85).

If you want to use url as the id, and assuming you have 'url' defined in your model in items.py, then it should should be simple as:

```
ELASTICSEARCH_UNIQ_KEY = 'url'
```

I have an example project https://github.com/jayzeng/dirbot illustrates how to use this plugin. Let me know if you have more questions.

**Comment by jayzeng** [comment]
@Feelthewind feel free to re-open the issue if you are confused or need any help
